version: '3.8'
services:
  sensorsapi:
    build: ./sensorsapi
    ports:
      - "8090:8090"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/sensor_db
    depends_on:
      - kafka
      - mongo

  sensorconsumer:
    build: ./sensorconsumer
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/sensor_db
    depends_on:
      - kafka
      - mongo

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=sensor_db
